### ISSUE TITLE
只用HintManager 批量插入时出错

### ISSUE THREAD

**Issue by jingshouyan** [shardingjdbc/sharding-jdbc#390]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.4.1
### Expected behavior
将数据插入指定的表
### Actual behavior
执行报错
### Steps to reproduce the behavior
表 BUDDY 分表分库键都是 userId 
### Please provide the reproduce example codes (such as github link) if possible.

List<Buddy> buddies = Lists.newArrayList();
        for (int i = 0; i < 12; i++) {
            Buddy buddy = new Buddy();
            buddy.setUserId(i+1001L);
            buddy.setBuddyId(i+2001L);
            buddy.forCreate();
            buddies.add(buddy);
        }
        HintManager hm = HintManager.getInstance();
        hm.addDatabaseShardingValue("BUDDY", "userId", 1L);
        hm.addTableShardingValue("BUDDY", "userId", 1L);
        buddyDao.insert(buddies);
        hm.close();

看日志应该是sql改写把values 全部丢弃了
log--------------------------------
2017-09-27 19:21:41,494 datasourceService INFO  [main] Sharding-JDBC-SQL: Actual SQL: user_01 ::: INSERT INTO buddy_01 (createdAt,deletedAt,id,buddyId,userId,updatedAt)  VALUES  ::: [1506511301225, 0, 119880343867097103, 2001, 1001, 1506511301225, 1506511301225, 0, 119880343867097104, 2002, 1002, 1506511301225, 1506511301225, 0, 119880343867097105, 2003, 1003, 1506511301225, 1506511301225, 0, 119880343867097106, 2004, 1004, 1506511301225, 1506511301225, 0, 119880343867097107, 2005, 1005, 1506511301225, 1506511301225, 0, 119880343867097108, 2006, 1006, 1506511301225, 1506511301225, 0, 119880343867097109, 2007, 1007, 1506511301225, 1506511301225, 0, 119880343867097110, 2008, 1008, 1506511301225, 1506511301225, 0, 119880343867097111, 2009, 1009, 1506511301225, 1506511301225, 0, 119880343867097112, 2010, 1010, 1506511301225, 1506511301225, 0, 119880343867097113, 2011, 1011, 1506511301225, 1506511301225, 0, 119880343867097114, 2012, 1012, 1506511301225]
2017-09-27 19:21:41,648 datasourceService INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader: Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2017-09-27 19:21:41,725 datasourceService INFO  [main] org.springframework.jdbc.support.SQLErrorCodesFactory: SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]

org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [INSERT INTO BUDDY (createdAt,deletedAt,id,buddyId,userId,updatedAt)  VALUES (?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?),(?,?,?,?,?,?)]; SQL state [null]; error code [0]; sql injection violation, syntax error: syntax error, expect ')', pos 79, line 1, column 80, token EOF : INSERT INTO buddy_01 (createdAt,deletedAt,id,buddyId,userId,updatedAt)  VALUES ; nested exception is java.sql.SQLException: sql injection violation, syntax error: syntax error, expect ')', pos 79, line 1, column 80, token EOF : INSERT INTO buddy_01 (createdAt,deletedAt,id,buddyId,userId,updatedAt)  VALUES 

	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:894)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:287)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:292)
	at com.jing.cloud.service.dao.impl.DbDaoImpl.insert(DbDaoImpl.java:128)
	at com.jing.cloud.service.dao.impl.DbDaoImpl$$FastClassBySpringCGLIB$$b4ed9a5d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.jing.cloud.service.buddy.dao.impl.BuddyDaoImpl$$EnhancerBySpringCGLIB$$4308baf2.insert(<generated>)
	at HintTest.dbTest(HintTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: java.sql.SQLException: sql injection violation, syntax error: syntax error, expect ')', pos 79, line 1, column 80, token EOF : INSERT INTO buddy_01 (createdAt,deletedAt,id,buddyId,userId,updatedAt)  VALUES 
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:725)
	at com.alibaba.druid.wall.WallFilter.connection_prepareStatement(WallFilter.java:301)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:523)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:949)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:155)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:523)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:384)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:422)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.generatePreparedStatement(ShardingPreparedStatement.java:178)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.route(ShardingPreparedStatement.java:156)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:128)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 42 more
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect ')', pos 79, line 1, column 80, token EOF
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2191)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2139)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:131)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:161)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:93)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:89)
	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:620)
	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:574)
	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:712)
	... 55 more

**Comment by terrymanu** [comment]
目前不支持批量插入，文档中已明确提及。如无特殊说明，请勿再测试既然a场景不支持，是否b场景会支持。这基本属于无用功，即使偶然支持也会当作bug，按照校验不严格处理
