### ISSUE TITLE
多表left join 出现SQL syntax error, expected token is 'EQ', actual token is 'IDENTIFIER', literals is 'sales'. 

### ISSUE THREAD

**Issue by babylikebird** [shardingjdbc/sharding-jdbc#433]
Caused by: io.shardingjdbc.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'EQ', actual token is 'IDENTIFIER', literals is 'sales'.
	at io.shardingjdbc.core.parsing.lexer.LexerEngine.accept(LexerEngine.java:107)
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parseJoinCondition(TableReferencesClauseParser.java:109)
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parseJoinTable(TableReferencesClauseParser.java:84)
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parseTableFactor(TableReferencesClauseParser.java:72)

**Comment by terrymanu** [comment]
请提供sql

**Comment by babylikebird** [comment]
SELECT
        SUM(sales.saleroom) AS saleroom,
        shop.sys_org_code AS orgCode,
        d.departname AS department,
        d.parentdepartid AS parentdepartid,
        d.ID AS departId
        FROM
        ec_sales AS sales
        LEFT JOIN ec_shop shop ON (sales.shop_id = shop.shop_id)
        LEFT JOIN t_s_depart d ON (
        d.org_code = shop.sys_org_code
        )
        WHERE
                shop.sys_org_code LIKE CONCAT('','${sqlParam.orgCode}','%' )
                AND
                data_date &gt;= #{sqlParam.startTime}
                AND
                data_date &lt;= #{sqlParam.endTime}
       
        GROUP BY
        shop.sys_org_code

**Comment by terrymanu** [comment]
sharding jdbc的sql中不允许出现schema或db的名字，这些都交给分片规则去处理

**Comment by terrymanu** [comment]
看起来可能是个解析sql的bug，我们看一下

**Comment by terrymanu** [comment]
不支持冗余括号，将SQL改为：

```sql
SELECT
SUM(sales.saleroom) AS saleroom,
shop.sys_org_code AS orgCode,
d.departname AS department,
d.parentdepartid AS parentdepartid,
d.ID AS departId
FROM
ec_sales AS sales
LEFT JOIN ec_shop shop ON sales.shop_id = shop.shop_id
LEFT JOIN t_s_depart d ON 
d.org_code = shop.sys_org_code 
WHERE
shop.sys_org_code LIKE CONCAT('','${sqlParam.orgCode}','%' )
AND
data_date >= #{sqlParam.startTime}
AND
data_date <= #{sqlParam.endTime}
```
即可
