### ISSUE TITLE
是否支持SELECT CURRENT_TIMESTAMP FROM DUAL

### ISSUE THREAD

**Issue by enaihei** [shardingjdbc/sharding-jdbc#449]
如题
`

    private static final String CURRENT_TIMESTAMP = "SELECT CURRENT_TIMESTAMP FROM DUAL";

    public Timestamp currentTimestamp() {
        return jdbcTemplate.queryForObject(CURRENT_TIMESTAMP, Timestamp.class);
    }

`
13:46:27.321 [http-nio-8080-exec-7] DEBUG c.d.d.r.s.r.s.SingleTableRouter - After table sharding DUAL result: [DUAL]
13:46:27.323 [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at com.dangdang.ddframe.rdb.sharding.parser.result.router.SQLBuilder$StringToken.access$300(SQLBuilder.java:233)
	at com.dangdang.ddframe.rdb.sharding.parser.result.router.SQLBuilder.buildSQLWithNewToken(SQLBuilder.java:155)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleRoutingTableFactor.buildSQL(SingleRoutingTableFactor.java:60)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleRoutingDataSource.getSQLExecutionUnits(SingleRoutingDataSource.java:57)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleRoutingResult.getSQLExecutionUnits(SingleRoutingResult.java:144)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:128)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.route(SQLRouteEngine.java:75)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.route(SQLRouteEngine.java:71)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingStatement.generateExecutor(ShardingStatement.java:278)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingStatement.executeQuery(ShardingStatement.java:118)
`

**Comment by terrymanu** [comment]
不支持

**Comment by enaihei** [comment]
如果我想获取数据库的时间。有什么办法吗？
