### ISSUE TITLE
查询条件中含有运算符时（如 -），SQL解析出错

### ISSUE THREAD

**Issue by zhangshixi** [shardingjdbc/sharding-jdbc#450]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
Sharding-JDBC：1.5.4.1
数据库MySQL
### Expected behavior
SQL查询返回正常结果
SELECT  due_date nextRepayDate, (order_id - 1) AS orderId
        FROM debt
        WHERE loan_id = #{loanId}
        and user_id = #{userId}
        AND status_id IN (0,4,5)
        ORDER BY order_id asc
        limit 1
### Actual behavior
The error may exist in file [D:\Workspace\jiedai\oius\oius-service\target\classes\conf\mybatis\mapper\ppdaiDebtMain\debt-mapper.xml]
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: SELECT  due_date nextRepayDate,(order_id-1) AS orderId         FROM debt         WHERE loan_id = ?         and user_id = ?         AND status_id IN (0,4,5)         ORDER BY order_id asc         limit 1
Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 103 common frames omitted
Caused by: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'
	at com.dangdang.ddframe.rdb.sharding.routing.type.complex.ComplexRoutingEngine.route(ComplexRoutingEngine.java:81)
	at com.dangdang.ddframe.rdb.sharding.routing.router.ParsingSQLRouter.route(ParsingSQLRouter.java:117)
	at com.dangdang.ddframe.rdb.sharding.routing.router.ParsingSQLRouter.route(ParsingSQLRouter.java:84)
	at com.dangdang.ddframe.rdb.sharding.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:57)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.route(ShardingPreparedStatement.java:149)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy159.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at ppdai.dbtracing.mybatis.CatMybatisPlugin.intercept(CatMybatisPlugin.java:86)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy157.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 110 common frames omitted

### Steps to reproduce the behavior
SpringBoot + Mybatis
之前使用1.4.2版本正常，升级到1.5.4.1后出错
跟踪代码发现
SelectListClauseParser.class -> parseSelectItem() 返回的结果，在解析完第二个查询项order_id 后，currentToken为 -1，而不是预期的FROM，导致后面没有解析table，然后出错。

盼回复！

**Comment by cocodroid** [comment]
经测试2.0.0.M2也有问题，应该是一个bug。分表的的时候执行查询，使用的还是逻辑表，造成表不存在。

**Comment by cocodroid** [comment]
1.5之后SQL解析去掉druid依赖，之后内部实现，所以你用1.5之前是正常的 @zhangshixi

**Comment by zhangshixi** [comment]
之前用的1.4.2是正常的，但现在要同时支持SQLServer和MySQL，所以要升级到1.5之后。 @cocodroid

**Comment by terrymanu** [comment]
这样的sql不适合跑在需要分片的互联网数据库在线查询中，我们不希望集中80%的精力处理20%的场景。因此不支持这种查询。

**Comment by zhangshixi** [comment]
您是指查询的字段不适合？还是指查询条件不适合？请说明
确实查询的字段可以修改，不在SQL中做运算。而您说的2/8原则，我想知道，这种SQL的解析，为什么老的版本支持，而在新版中不在支持，是基于何种原因考虑的？
