### ISSUE TITLE
dynamic update zk datenode of shardingDatasource occurred exception

### ISSUE THREAD

**Issue by comenglish** [shardingjdbc/sharding-jdbc#453]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
2.0.0.M2
### Expected behavior
no exception and update data node successful!
### Actual behavior
occurred exception, such as:
2017-11-20 17:35:52 - [Curator-TreeCache-1] - ERROR - TreeCache:751 - 
java.lang.IllegalArgumentException: Invalid format for actual data nodes: 'traceHisDataSource.a_trace_his{0..2}'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at io.shardingjdbc.core.rule.TableRule.generateDataNodes(TableRule.java:75)
	at io.shardingjdbc.core.rule.TableRule.<init>(TableRule.java:57)
	at io.shardingjdbc.core.api.config.TableRuleConfiguration.build(TableRuleConfiguration.java:68)
	at io.shardingjdbc.core.api.config.ShardingRuleConfiguration.build(ShardingRuleConfiguration.java:73)
	at io.shardingjdbc.orchestration.internal.config.ConfigurationService$1.childEvent(ConfigurationService.java:111)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
### Steps to reproduce the behavior
config the reg:zookeeper and    [<sharding:data-source id="shardingDataSource"  registry-center-ref="regCenter" overwrite="true">],
update zk datenode " /orchestration-spring-namespace/shardingDataSource/config/sharding" and then occurred this exception!

**Comment by comenglish** [comment]
update data:
 set /orchestration-spring-namespace/shardingDataSource/config/sharding {"tableRuleConfigs":[{"logicTable":"a_trace_his","actualDataNodes":"a_trace_his{0..3}","databaseShardingStrategyConfig":{},"tableShardingStrategyConfig":{"type":"STANDARD","shardingColumn":"CUT_DATE","preciseAlgorithmClassName":"com.zx.common.dataSource.TraceTableShardingAlgorithm","rangeAlgorithmClassName":"com.zx.common.dataSource.TraceTableRangeShardingAlgorithm"},"keyGeneratorColumnName":"CUT_DATE"}],"bindingTableGroups":["a_trace_his"],"defaultDatabaseShardingStrategyConfig":{},"defaultTableShardingStrategyConfig":{},"masterSlaveRuleConfigs":[]}

**Comment by haocao** [comment]
应该配置为a_trace_his${0..3}

**Comment by terrymanu** [comment]
报错信息已经很明显了，inline表达式格式配置错误

**Comment by comenglish** [comment]
而Spring命名空间配置 章节讲得非常清楚，所有的配置都是：actual-data-nodes="dbtbl_${0..1}.t_order_${0..3}"
数据库名.表名

**Comment by comenglish** [comment]
如果能统一规则是不是更好？

**Comment by comenglish** [comment]
更正：

> 
set  /orchestration-spring-namespace/shardingDataSource/config/sharding
{"tableRuleConfigs":[{"logicTable":"a_trace_his","actualDataNodes":"traceHisDataSource.a_trace_his_${0..1}","databaseShardingStrategyConfig":{},"tableShardingStrategyConfig":{"type":"STANDARD","shardingColumn":"CUT_DATE","preciseAlgorithmClassName":"com.zx.common.dataSource.TraceTableShardingAlgorithm","rangeAlgorithmClassName":"com.zx.common.dataSource.TraceTableRangeShardingAlgorithm"},"keyGeneratorColumnName":"CUT_DATE"}],"bindingTableGroups":["a_trace_his"],"defaultDatabaseShardingStrategyConfig":{},"defaultTableShardingStrategyConfig":{},"masterSlaveRuleConfigs":[]}

一样会报错：

2017-11-21 14:09:41 - [Curator-TreeCache-1] - ERROR - TreeCache:751 - 
java.lang.IllegalArgumentException: Cannot find data source name in sharding rule, invalid actual data node is: 'traceHisDataSource.a_trace_his_0'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at io.shardingjdbc.core.rule.TableRule.generateDataNodes(TableRule.java:77)
	at io.shardingjdbc.core.rule.TableRule.<init>(TableRule.java:57)
	at io.shardingjdbc.core.api.config.TableRuleConfiguration.build(TableRuleConfiguration.java:68)
	at io.shardingjdbc.core.api.config.ShardingRuleConfiguration.build(ShardingRuleConfiguration.java:73)
	at io.shardingjdbc.orchestration.internal.config.ConfigurationService$1.childEvent(ConfigurationService.java:111)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by comenglish** [comment]
![image](https://user-images.githubusercontent.com/3346009/33057524-699f4bfa-cec6-11e7-8e0d-8d7a1456b4c9.png)

**Comment by comenglish** [comment]
![image](https://user-images.githubusercontent.com/3346009/33057548-7f6a4e76-cec6-11e7-9cbc-a423943a6fc3.png)

**Comment by haocao** [comment]
请把完整demo代码提交到github上以便复现

**Comment by comenglish** [comment]
https://github.com/comenglish/shardingDemo.git

**Comment by comenglish** [comment]
经测试，使用官方的例子，修改zk node 中的信息，并不会动态设置数据源。而且，数据源读取到的还是原来的信息。
无法监听些问题。
只能使用spring-mvc web 工程能轻易复现该问题

**Comment by comenglish** [comment]
简化问题后，测试举例：
    private static String json="[{\"name\":\"traceHisDataSource\",\"clazz\":\"com.alibaba.druid.pool.DruidDataSource\",\"connectionErrorRetryAttempts\":\"30\",\"dbType\":\"mysql\",\"driverClassName\":\"com.mysql.jdbc.Driver\",\"exceptionSorterClassName\":\"com.alibaba.druid.pool.vendor.MySqlExceptionSorter\",\"initialSize\":\"10\",\"loginTimeout\":\"0\",\"maxActive\":\"100\",\"maxCreateTaskCount\":\"3\",\"maxEvictableIdleTimeMillis\":\"25200000\",\"maxIdle\":\"8\",\"maxOpenPreparedStatements\":\"10\",\"maxPoolPreparedStatementPerConnectionSize\":\"10\",\"maxWait\":\"60000\",\"maxWaitThreadCount\":\"-1\",\"minEvictableIdleTimeMillis\":\"1800000\",\"minIdle\":\"10\",\"name\":\"DataSource-1772295012\",\"notFullTimeoutRetryCount\":\"0\",\"numTestsPerEvictionRun\":\"3\",\"password\":\"xingdata\",\"phyTimeoutMillis\":\"-1\",\"queryTimeout\":\"0\",\"removeAbandonedTimeout\":\"300\",\"removeAbandonedTimeoutMillis\":\"300000\",\"timeBetweenConnectErrorMillis\":\"30000\",\"timeBetweenEvictionRunsMillis\":\"60000\",\"timeBetweenLogStatsMillis\":\"0\",\"transactionQueryTimeout\":\"0\",\"transactionThresholdMillis\":\"0\",\"url\":\"jdbc:mysql://databaseurl:3306/db_t_test?useUnicode\\u003dtrue\\u0026characterEncoding\\u003dUTF-8\\u0026useSSL\\u003dfalse\\u0026allowMultiQueries\\u003dtrue\",\"username\":\"root\",\"validConnectionCheckerClassName\":\"com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker\",\"validationQuery\":\"SELECT \\u0027x\\u0027 FROM DUAL\",\"validationQueryTimeout\":\"-1\"}]";
    
    public static void main(String[] args) {
        Map<String, DataSource> result = new LinkedHashMap<>();
        List<NamedDataSource> namedDataSources = GsonFactory.getGson().fromJson(json, new TypeToken<List<NamedDataSource>>(){}.getType());
        for(NamedDataSource source : namedDataSources) {
            System.out.println(source.getName());
        }
    }

**Comment by comenglish** [comment]
所以问题出现的原因
1.使用DruidAbstractDataSource 作为数据源 
2.使用zk 来存储 json格式的分表策略时要小心了。
3.NamedDataSource 的name 属性 被DruidAbstractDataSource 的name属性值 给覆盖了，造成的结果就是：从zk中获取结点数据，生成对象时，生成的 name值已非自已定义的数据源了。
因此：给出的建议是，在生成json时，注意检查对应的key为name的属性，不允许再出现。

**Comment by comenglish** [comment]
解决方案如下：
![image](https://user-images.githubusercontent.com/3346009/33157477-50e8a6e2-d03d-11e7-8acb-402aba3f7122.png)
修改类名：io.shardingjdbc.orchestration.internal.json.DataSourceGsonTypeAdapter

**Comment by comenglish** [comment]
测试用例：DataSourceJsonConverterTest.createDataSource(final String dataSourceName) 中请使用接口javax.sql.DataSource, 实现类请使用阿里的com.alibaba.druid.pool.DruidDataSource,如下：

> DataSource result = new com.alibaba.druid.pool.DruidDataSource();

方能验证该问题。
非常感谢官方如此迅速的答复
