### ISSUE TITLE
不支持create index语句

### ISSUE THREAD

**Issue by alulu-zh** [shardingjdbc/sharding-jdbc#475]
Please answer these questions before submitting your issue. Thanks!

### Expected behavior
jpa会通过create index语句来创建索引，但是sharding jdbc只支持create table语句。
error log:

```
Caused by: io.shardingjdbc.core.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'INDEX'.
	at io.shardingjdbc.core.parsing.lexer.LexerEngine.unsupportedIfNotSkip(LexerEngine.java:184) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.parsing.parser.sql.ddl.create.AbstractCreateParser.parse(AbstractCreateParser.java:54) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.parsing.parser.sql.ddl.create.AbstractCreateParser.parse(AbstractCreateParser.java:35) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:50) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.routing.router.ParsingSQLRouter.parse(ParsingSQLRouter.java:72) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.routing.StatementRoutingEngine.route(StatementRoutingEngine.java:47) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.jdbc.core.statement.ShardingStatement.generateExecutor(ShardingStatement.java:191) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at io.shardingjdbc.core.jdbc.core.statement.ShardingStatement.executeUpdate(ShardingStatement.java:110) ~[sharding-jdbc-core-2.0.0.M3.jar:na]
	at org.hibernate.tool.schema.internal.TargetDatabaseImpl.accept(TargetDatabaseImpl.java:56) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlString(SchemaMigratorImpl.java:431) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlStrings(SchemaMigratorImpl.java:420) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applyIndexes(SchemaMigratorImpl.java:283) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigrationToTargets(SchemaMigratorImpl.java:184) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:60) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:134) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:101) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:472) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]

```

**Comment by terrymanu** [comment]
finished  at 2.0.2
