### ISSUE TITLE
全路由关联查询时选择表的的问题

### ISSUE THREAD

**Issue by wangdengyang** [shardingjdbc/sharding-jdbc#482]
版本：2.0.0.M3
问题描述：逻辑表A、B各自有分表A_0、A_1，B_0、B_1、B_2，A与B是不同的策略类，当A与B进行selectAll的关联查询时，为什么sql运行是A_0对应B_0，A_1对应B1，然后多出一个B_2，报IndexOutOfBoundsException
不应该是A_0和A_1分别都对应一次B_0、B_1、B_2吗？
如以下日志，两个表的策略不同，查询sql却只有2条，不应该是4条吗？
[INFO ] 2017-12-06 15:52:17,190 --main-- [Sharding-JDBC-SQL] Logic SQL: SELECT
        i.*
        FROM
        t_order o, t_order_item i
        WHERE
        o.order_id = i.order_id 
[INFO ] 2017-12-06 15:52:17,190 --main-- [Sharding-JDBC-SQL] SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=t_order, alias=Optional.of(o)), Table(name=t_order_item, alias=Optional.of(i))]), conditions=Conditions(conditions={}), sqlTokens=[TableToken(beginPosition=40, originalLiterals=t_order), TableToken(beginPosition=51, originalLiterals=t_order_item)], parametersIndex=0)), containStar=false, selectListLastPosition=27, groupByLastPosition=0, items=[CommonSelectItem(expression=i.*, alias=Optional.absent())], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null) 
[INFO ] 2017-12-06 15:52:17,190 --main-- [Sharding-JDBC-SQL] Actual SQL: dataSource ::: SELECT
        i.*
        FROM
        t_order_2016 o, t_order_item_2016 i
        WHERE
        o.order_id = i.order_id 
[INFO ] 2017-12-06 15:52:17,190 --main-- [Sharding-JDBC-SQL] Actual SQL: dataSource ::: SELECT
        i.*
        FROM
        t_order_2017 o, t_order_item_2017 i
        WHERE
        o.order_id = i.order_id 
[]

**Comment by terrymanu** [comment]
请提供具体的配置信息，以及报错信息。
我从您提供的信息并未看到任何错误，order和order_item表的2016和2017都是匹配对应的

**Comment by wangdengyang** [comment]
我不清楚的是order和order_item两个表的分表策略不一样，为什么是匹配对应的呢
配置如下：
	```
<!-- sharding jdbc改动处 -->
	<sharding:standard-strategy id="orderTableShardingStrategy" sharding-column="SOD_CREATE_TIME" precise-algorithm-class="com.msonion.web.util.shardingjdbc.PreciseModuloTableShardingAlgorithm"/>
    <sharding:standard-strategy id="orderItemTableShardingStrategy" sharding-column="SOD_ITEM_CREATE_TIME" precise-algorithm-class="com.msonion.web.util.shardingjdbc.PreciseModuloTableShardingAlgorithm2"/>
    
    <sharding:data-source id="shardingDataSource">
        <sharding:sharding-rule data-source-names="dataSource">
            <sharding:table-rules>
                <sharding:table-rule logic-table="t_order" actual-data-nodes="dataSource.t_order_${2016..2018}" table-strategy-ref="orderTableShardingStrategy" generate-key-column="order_id" />
                <sharding:table-rule logic-table="t_order_item" actual-data-nodes="dataSource.t_order_item_${2016..2017}" table-strategy-ref="orderItemTableShardingStrategy" generate-key-column="order_item_id" />
            </sharding:table-rules>
            <sharding:binding-table-rules>
                <sharding:binding-table-rule logic-tables="t_order, t_order_item"/>
            </sharding:binding-table-rules>
        </sharding:sharding-rule>
        <sharding:props>
        	<prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>
```
两个策略类：
策略类一：
```
public final class PreciseModuloTableShardingAlgorithm implements PreciseShardingAlgorithm<Date> {
    
	@Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Date> shardingValue) {
//		Calendar instance = Calendar.getInstance();
//		instance.setTime(shardingValue.getValue());
//		int year = instance.get(Calendar.YEAR);
    	for (String each : availableTargetNames) {
            if (each.endsWith(2017+ "")) {
                return each;
            }
        }
        throw new UnsupportedOperationException();
    }
}

```
策略类一：
```
public final class PreciseModuloTableShardingAlgorithm2 implements PreciseShardingAlgorithm<Date> {
    
	@Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Date> shardingValue) {
//		Calendar instance = Calendar.getInstance();
//		instance.setTime(shardingValue.getValue());
//		int year = instance.get(Calendar.YEAR);
    	for (String each : availableTargetNames) {
            if (each.endsWith(2016+ "")) {
                return each;
            }
        }
        throw new UnsupportedOperationException();
    }
}

```
运行demo方法，当走到System.out.println(orderItemRepository.selectAll());时
报错信息如下：
Exception in thread "main" org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:365)
	at com.sun.proxy.$Proxy19.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:195)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:120)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:90)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:40)
	at com.sun.proxy.$Proxy40.selectAll(Unknown Source)
	at com.msonion.core.service.DemoService.demo(DemoService.java:49)
	at com.msonion.core.SpringMybatisShardingTableOnlyMain.main(SpringMybatisShardingTableOnlyMain.java:33)

**Comment by terrymanu** [comment]
请自行google一下错误信息The error occurred while setting parameters
这是mybatis和sql的参数不匹配，错误与sharding-jdbc无关。

另外，多说一句，请问这个分片策略的配置是什么意思：
dataSource.t_order_${2016..2018}和dataSource.t_order_item_${2016..2017}
t_order_item无需2018年的数据？
sharding-jdbc是水平扩展的分库分表中间件。

**Comment by wangdengyang** [comment]
@terrymanu 其实问题描述的越多越容易把问题带偏，我想问的核心就是我描述第一栏里的前几行文字内容。
上面我贴的配置和策略类其实跟年份和表名都没什么关系，就是想表达A表和B表的分表数量不一致，策略也不一致，但是两者关联查询全路由时，却发生异常，触发异常的是A和B的分表数量不一致，只要两者分表数量一致就不会有异常。
因为异常全贴出来比较占篇幅，非常抱歉上面异常没贴完整
异常信息：
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:355)
	... 8 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.LinkedList.checkElementIndex(LinkedList.java:553)
	at java.util.LinkedList.get(LinkedList.java:474)
	**at io.shardingjdbc.core.rule.BindingTableRule.getBindingActualTable(BindingTableRule.java:76)**
	at io.shardingjdbc.core.rewrite.SQLRewriteEngine.getBindingTableTokens(SQLRewriteEngine.java:236)
	at io.shardingjdbc.core.rewrite.SQLRewriteEngine.getTableTokens(SQLRewriteEngine.java:215)
	at io.shardingjdbc.core.rewrite.SQLRewriteEngine.generateSQL(SQLRewriteEngine.java:196)
	at io.shardingjdbc.core.routing.router.ParsingSQLRouter.route(ParsingSQLRouter.java:100)
	at io.shardingjdbc.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:57)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.route(ShardingPreparedStatement.java:150)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:140)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:57)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy93.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:141)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:98)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:73)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:101)
	... 14 more

**Comment by terrymanu** [comment]
哦，明白了。这个是配置了BindingTableRule导致。BindingTable的意思是两组表的分片规则必须完全一致才可以。
你的示例中所表达的意思，是两组表的分片规则不一致，因此就不应该配置BindingTableRule。删除BindingTableRule应该就可以了，但是查询效率较低，会采取笛卡尔积查询

**Comment by wangdengyang** [comment]
@terrymanu 其实就算是A表和B表都分为同样数量的两个表，这种情况不会异常，但两者策略不一样，为什么还是会有A_0对应B_a，A_1对应B_b的匹配关系呢，强调是两者分表策略不一样的

**Comment by terrymanu** [comment]
两组分片规则不同的表，不应该配置BindingTableRule

**Comment by wangdengyang** [comment]
@terrymanu 好的，刚看到你的回复，我试一下，非常感谢亮哥的回复
