### ISSUE TITLE
循环进行查询报错

### ISSUE THREAD

**Issue by wangzhenhua-bijie** [shardingjdbc/sharding-jdbc#512]
### Cause: java.lang.NullPointerException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at com.sun.proxy.$Proxy115.selectOne(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-1.3.1.jar:1.3.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy130.selectByPrimaryKey(Unknown Source) ~[?:?]
	at com.ai.business.coin.AddressBalanceBusiness.lambda$0(AddressBalanceBusiness.java:29) ~[classes/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_151]
	at com.ai.business.coin.AddressBalanceBusiness.saveBatch(AddressBalanceBusiness.java:28) ~[classes/:?]
	at com.ai.business.coin.AddressBalanceBusiness$$FastClassBySpringCGLIB$$b8068d08.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.ai.business.coin.AddressBalanceBusiness$$EnhancerBySpringCGLIB$$bdcedb7.saveBatch(<generated>) ~[classes/:?]
	at com.ai.business.ws.CoinMonitorAbstract.saveAddressBalance(CoinMonitorAbstract.java:115) ~[classes/:?]
	at com.ai.business.ws.ArkWs$QueryBalanceTask.run(ArkWs.java:217) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77) ~[mybatis-3.4.5.jar:3.4.5]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
	... 27 more
Caused by: java.lang.NullPointerException
	at io.shardingjdbc.core.merger.MergeEngine.getColumnLabelIndexMap(MergeEngine.java:59) ~[sharding-jdbc-core-2.0.1.jar:?]
	at io.shardingjdbc.core.merger.MergeEngine.<init>(MergeEngine.java:55) ~[sharding-jdbc-core-2.0.1.jar:?]
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.getResultSet(ShardingPreparedStatement.java:274) ~[sharding-jdbc-core-2.0.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:69) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy125.getResultSet(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:235) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:185) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:60) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.4.5.jar:3.4.5]
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:143) ~[pagehelper-5.1.2.jar:?]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.5.jar:3.4.5]
	at com.sun.proxy.$Proxy124.query(Unknown Source) ~[?:?]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77) ~[mybatis-3.4.5.jar:3.4.5]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar:1.3.1]
	... 27 more

**Comment by wangzhenhua-bijie** [comment]
第一次查询可以查询到结果，第二次出现错误

**Comment by wangzhenhua-bijie** [comment]
addressBalanceList.forEach(e->{
			this.addressBalanceMapper.selectByPrimaryKey(e.getCoin(), e.getAddress());
		});

**Comment by terrymanu** [comment]
看起来好像是个bug，不过您提供的信息不足以重现。
请提供可以重现的代码

**Comment by terrymanu** [comment]
请将可重现问题的代码提交至github，并将链接发送过来，谢谢

**Comment by wangzhenhua-bijie** [comment]
public interface AddressBalanceMapper {
    AddressBalance selectByPrimaryKey(@Param("coin")String coin,@Param("address")String address);
}
<resultMap id="BaseResultMap" type="com.ai.models.coin.AddressBalance">
		<id column="coin" jdbcType="VARCHAR" property="coin" />
		<id column="address" jdbcType="VARCHAR" property="address" />
		<result column="node" jdbcType="VARCHAR" property="node" />
		<result column="balance" jdbcType="DECIMAL" property="balance" />
		<result column="unlocked_balance" jdbcType="DECIMAL" property="unlockedBalance" />
		<result column="sweepable_balance" jdbcType="DECIMAL" property="sweepableBalance" />
		<result column="update_time" jdbcType="TIMESTAMP" property="updateTime" />
	</resultMap>
	<sql id="Base_Column_List">
		node,coin, address, balance, unlocked_balance, sweepable_balance, update_time
	</sql>
	<select id="selectByPrimaryKey" resultMap="BaseResultMap">
		select
		<include refid="Base_Column_List" />
		from address_balance
		where coin = #{coin,jdbcType=VARCHAR}
		and address = #{address,jdbcType=VARCHAR}
	</select>

**Comment by terrymanu** [comment]
目前的信息难于重现，请将可重现问题的代码提交至github，并将链接发送过来，谢谢

**Comment by wangzhenhua-bijie** [comment]
我测试出问题的原因了
config.setDefaultExecutorType(ExecutorType.REUSE);这种模式会报The error occurred while handling results错误
config.setDefaultExecutorType(ExecutorType.SIMPLE);这种模式就不会报错了可以正常查询

**Comment by wangzhenhua-bijie** [comment]
原因应该是shardingjdbc对预处理sql的问题

**Comment by haocao** [comment]
目前的信息难于重现，能否将可重现问题的代码提交至github？谢谢
