### ISSUE TITLE
SQL中含科学计算的排序不支持

### ISSUE THREAD

**Issue by Mailerm** [shardingjdbc/sharding-jdbc#526]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
1.5.4.1
### Expected behavior
正常返回
#### 执行SQL：
SELECT    p.*   FROM    _park p          WHERE  p.`status` = 1                                                                          Order by        (         3959 * ACOS(           COS(RADIA
NS(?)) * COS(RADIANS(latitude)) * COS(             RADIANS(longitude) - RADIANS(?)           ) + SIN(RADIANS(?)) * SIN(RADIANS(latitude))         )       ) ASC    LIMIT ?,?

#### 异常：
Caused by: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException:
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS ORDER_BY_DERIVED_0 FROM
                        _park p
                 WHERE  p.`status` = 1
                ' at line 3
        at com.dangdang.ddframe.rdb.sharding.executor.threadlocal.ExecutorExceptionHandler.handleException(ExecutorExceptionHandler.java:61)
        at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.execute(ExecutorEngine.java:129)
        at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.executePreparedStatement(ExecutorEngine.java:96)
        at com.dangdang.ddframe.rdb.sharding.executor.type.prepared.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:93)
        at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:140)
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)

**Comment by terrymanu** [comment]
这种排序无法支持，需要全库表扫描了，在分片的数据库中执行这样的sql，无异于杀死系统。
sharding-jdbc是面向互联网场景的实时在线业务，因此不会对这样的查询进行支持，请知晓
