### ISSUE TITLE
sharding-jdbc使用yaml+etcd做配置，启动失败

### ISSUE THREAD

**Issue by mzanthem** [shardingjdbc/sharding-jdbc#536]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?

demo:sharding-jdbc-orchestration-etcd-yaml-example：master分支2.0.0

sharding-jdbc-core:2.0.1

### Expected behavior
使用etcd做编排治理，实现数据源、表与分片及读写分离策略的动态切换
### Actual behavior

启动失败：
```java
Exception in thread "main" java.lang.NullPointerException
	at io.shardingjdbc.orchestration.api.OrchestrationShardingDataSourceFactory.createDataSource(OrchestrationShardingDataSourceFactory.java:77)
	at io.shardingjdbc.example.orchestration.yaml.OrchestrationEtcdYamlShardingMain.main(OrchestrationEtcdYamlShardingMain.java:40)

```

### Steps to reproduce the behavior
1.按照[文档](http://shardingjdbc.io/docs/02-guide/orchestration/)把配置信息写入到etcd(使用etcd4jTest);
2.把`yamlShardingDatabaseAndTable.yaml`中的信息除orchestration节点外，全部删除；
3.执行`OrchestrationEtcdYamlShardingMain.java`

### Please provide the reproduce example codes (such as github link) if possible.
[sharding-jdbc-orchestration-etcd-yaml-example]()

[etc4jTest](https://github.com/mzanthem/etcd4jTest)

**Comment by haocao** [comment]
Duplicate with #537.
