### ISSUE TITLE
sharding 是否支持批量更新操作

### ISSUE THREAD

**Issue by hwck** [shardingjdbc/sharding-jdbc#561]
在跟mybatis整合的时候，批量更新t_order_item 表的status,使用如下语句报错

interface
    void updateStatus(List<Long> orderItemIds);

mapper
 <update id="updateStatus" parameterType="java.util.List">
        update t_order_item set status = 1
        where  in order_id
        <foreach collection="list" item="item" index="index" open="(" close=")" separator=",">
            #{item.orderId}
        </foreach>
    </update>

orderItemRepository.updateStatus(orderIds)

Exception in thread "main" org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'orderId' in 'class java.lang.Long'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:79)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy10.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:295)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy13.updateStatus(Unknown Source)
	at io.shardingjdbc.example.spring.namespace.mybatis.service.DemoService.demo(DemoService.java:49)
	at io.shardingjdbc.example.spring.namespace.mybatis.SpringMybatisShardingDatabaseOnlyMain.main(SpringMybatisShardingDatabaseOnlyMain.java:32)
Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'orderId' in 'class java.lang.Long'
	at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:422)
	at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:119)
	at org.apache.ibatis.mapping.BoundSql.getAdditionalParameter(BoundSql.java:74)
	at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:72)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.parameterize(PreparedStatementHandler.java:93)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.parameterize(RoutingStatementHandler.java:64)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 7 more

**Comment by terrymanu** [comment]
duplicate with #563
