### ISSUE TITLE
在批量插入的时候报错

### ISSUE THREAD

**Issue by hwck** [shardingjdbc/sharding-jdbc#563]
插入多条时候报错，如果批量操作，直插入一条时没有问题

```
### Error updating database.  Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '__frch_item_0'. It was either not specified and/or could not be found for the javaType (io.shardingjdbc.example.spring.namespace.mybatis.entity.Order) : jdbcType (OTHER) combination.
### Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property '__frch_item_0'. It was either not specified and/or could not be found for the javaType (io.shardingjdbc.example.spring.namespace.mybatis.entity.Order) : jdbcType (OTHER) combination.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:79)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:447)
	at com.sun.proxy.$Proxy10.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:279)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy11.batchInserts(Unknown Source)
	at io.shardingjdbc.example.spring.namespace.mybatis.service.DemoService.demo(DemoService.java:62)
	at io.shardingjdbc.example.spring.namespace.mybatis.SpringMybatisShardingDatabaseOnlyMain.main(SpringMybatisShardingDatabaseOnlyMain.java:32)
```

```java
        List<Order> orders = new ArrayList<>();
        Order o1 = new Order();
        o1.setUserId(800);
        o1.setStatus("111111111test");
        orders.add(o1);

        Order o2 = new Order();
        o2.setUserId(801);
        o2.setStatus("2222222222222222");
        orders.add(o2);
        orderRepository.batchInserts(orders);
        System.out.println(orderRepository.selectAll());
```

interface
```java
    void batchInserts(List<Order> model);
```

mapper

```xml
    <insert id="batchInserts" parameterType="java.util.List">
        insert into t_order(
        user_id,
        status
        ) values
        <foreach collection="list" item="item" index="index" separator=",">
            (
            #{item}
            )
        </foreach>
    </insert>
```

**Comment by hwck** [comment]
批量更新的时候，可以批量更新

**Comment by terrymanu** [comment]
请将可运行的代码以及建表语句提交至您github的私人repo，我们需要根据代码重现这个问题。

**Comment by terrymanu** [comment]
请仔细阅读文档。不支持sql部分
