### ISSUE TITLE
sharding jdbc不支持批量操作了，插入、删除、更新？

### ISSUE THREAD

**Issue by XueGeng** [shardingjdbc/sharding-jdbc#606]
### Cause: io.shardingjdbc.core.exception.ShardingJdbcException: Invoke jdbc method exception
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 7 more

**Comment by terrymanu** [comment]
您的问题文档中都有，我就不再单独回答了，谢谢理解

**Comment by lintghi** [comment]
sharding jdbc不支持批量操作是只針對分表的表還是所有表?
