### ISSUE TITLE
数据源中非分表的表查询及插入问题

### ISSUE THREAD

**Issue by Leowang628** [shardingjdbc/sharding-jdbc#640]
### Which version of Sharding-Jdbc do you using?
2.0.3

### Expected behavior 
数据源只有一张表(t_fm_order_check)需要分表，其他表不需要分表，所以只配置了一个sharding:table-rule

### Actual behavior 
这样未分表的表普通查询没什么问题，但是未分表的表联合查询（如：t_to_parent_order、t_to_sub_order）时会抛异常：java.lang.UnsupportedOperationException: Cannot support Multiple-Table、
未分表的表数据库主键id自增，但是使用mybatis插入时会显示column 'id' can not be null、且未分表的表不支持insertBatch

### Steps to reproduce the behavior 
UPDATE t_to_parent_order a INNER JOIN t_to_sub_order b ON a.source_id = b.parent_order_id set a.is_delete = 1    where  a.source_create_time >= ?     AND a.source_create_time < ?

### Exception detail:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.UnsupportedOperationException: Cannot support Multiple-Table.

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy32.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:254)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:49)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:43)
	at com.sun.proxy.$Proxy44.deleteWithDate(Unknown Source)
	at com.rrx.checkfinance.ShardingTest.testQuery(ShardingTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:85)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:86)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:241)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.UnsupportedOperationException: Cannot support Multiple-Table.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	... 34 more
Caused by: java.lang.UnsupportedOperationException: Cannot support Multiple-Table.
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parseTableFactor(TableReferencesClauseParser.java:81)
	at io.shardingjdbc.core.parsing.parser.dialect.mysql.clause.MySQLTableReferencesClauseParser.parseTableReference(MySQLTableReferencesClauseParser.java:24)
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parse(TableReferencesClauseParser.java:54)
	at io.shardingjdbc.core.parsing.parser.sql.dml.update.AbstractUpdateParser.parse(AbstractUpdateParser.java:52)
	at io.shardingjdbc.core.parsing.parser.sql.dml.update.AbstractUpdateParser.parse(AbstractUpdateParser.java:37)
	at io.shardingjdbc.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:50)
	at io.shardingjdbc.core.routing.router.ParsingSQLRouter.parse(ParsingSQLRouter.java:74)
	at io.shardingjdbc.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:55)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.route(ShardingPreparedStatement.java:150)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:140)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy38.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
	... 39 more

### XML配置

<bean name="checkfinanceDataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init"
      destroy-method="close" parent="dbCommProperty">
    <property name="url" value="${jdbc.url}"/>
    <property name="username" value="${jdbc.username}"/>
    <property name="password" value="${jdbc.password}"/>
    <property name="driverClassName" value="${jdbc.driver}"/>
</bean>

<sharding:standard-strategy id="tfmOrderCheckTableShardingStrategy" sharding-column="node2_order_time" precise-algorithm-class="com.rrx.checkfinance.algorithm.PreciseTfmOrderCheckShardingAlgorithm"
                            range-algorithm-class="com.rrx.checkfinance.algorithm.RangeTfmOrderCheckShardingAlgorithm"/>

<sharding:data-source id="financeCheckShardingDataSource">
    <sharding:sharding-rule data-source-names="checkfinanceDataSource" default-data-source-name="checkfinanceDataSource">
        <sharding:table-rules>
            <sharding:table-rule logic-table="t_fm_order_check" actual-data-nodes="checkfinanceDataSource.t_fm_order_check_${0..10}" table-strategy-ref="tfmOrderCheckTableShardingStrategy" />
        </sharding:table-rules>
    </sharding:sharding-rule>
</sharding:data-source>

 
 <bean id="dataSource" class="com.rrx.common.datasource.DataSources">
        <property name="targetDataSources">
            <map key-type="java.lang.String">
                <entry value-ref="financeCheckShardingDataSource" key="financeCheckShardingDataSource"></entry>
                <entry value-ref="checkfinanceDataSource" key="checkfinanceDataSource"></entry>
                <entry value-ref="rrcDataSource" key="rrcDataSource"></entry>
                <entry value-ref="repayDataSource" key="repayDataSource"></entry>
            </map>
    </property>
    <property name="defaultTargetDataSource" ref="financeCheckShardingDataSource"></property>
</bean>

<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
    
    <property name="dataSource" ref="dataSource"/>
    <property name="mapperLocations" value="classpath*:mappers/*Mapper.xml"/>
    <property name="plugins">
        <array>
            <bean class="com.github.pagehelper.PageHelper">
                <property name="properties">
                    <value>
                        dialect=mysql
                    </value>
                </property>
            </bean>
        </array>
    </property>
</bean>

**Comment by Leowang628** [comment]
[applicationContext-mybatis.txt](https://github.com/shardingjdbc/sharding-jdbc/files/1795872/applicationContext-mybatis.txt)

**Comment by terrymanu** [comment]
cannot support update more than one table in update SQL

**Comment by Leowang628** [comment]
OK,Thanks for your help~
