### ISSUE TITLE
Caused by: java.lang.NullPointerException: null 	at io.shardingjdbc.spring.boot.SpringBootConfiguration.setDataSourceMap(SpringBootConfiguration.java:55) ~[sharding-jdbc-core-spring-boot-starter-2.0.3.jar:na]

### ISSUE THREAD

**Issue by jixiaod** [shardingjdbc/sharding-jdbc#643]
Please answer these questions before submitting your issue. Thanks!
使用DataSourceUtil的编程方式连接数据源

`
@Configuration
@MapperScan("com.knowbox.kms.tiku.dao")
public class MyBatisConfig {

    private static final String URL_PREFIX = "jdbc:mysql://127.0.0.1:3306/";

    private static final String USER_NAME = "test";

    private static final String PASSWORD = "test";

    @Bean
    @Primary
    public static SqlSessionFactoryBean createSqlSessionFactoryBean() throws SQLException, IOException {

        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        // 设置mybatis configuration 扫描路径
        sqlSessionFactoryBean.setConfigLocation(new ClassPathResource("META-INF/mybatis-config.xml"));

        // 添加mapper 扫描路径
        PathMatchingResourcePatternResolver pathMatchingResourcePatternResolver = new PathMatchingResourcePatternResolver();
        sqlSessionFactoryBean.setMapperLocations(pathMatchingResourcePatternResolver.getResources(ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX + "/META-INF/mapper/*.xml"));

        // 设置datasource
        DataSource dataSource = getMasterSlaveDataSource();
        sqlSessionFactoryBean.setDataSource(dataSource);
        return sqlSessionFactoryBean;
    }

    private static DataSource getMasterSlaveDataSource() throws SQLException {
        MasterSlaveRuleConfiguration masterSlaveRuleConfig = new MasterSlaveRuleConfiguration();
        masterSlaveRuleConfig.setName("ds_master_slave");
        masterSlaveRuleConfig.setMasterDataSourceName("ds_master");
        masterSlaveRuleConfig.setSlaveDataSourceNames(Arrays.asList("ds_slave_0", "ds_slave_1"));
        return MasterSlaveDataSourceFactory.createDataSource(createDataSourceMap(), masterSlaveRuleConfig, new ConcurrentHashMap<>());
    }

    private static Map<String, DataSource> createDataSourceMap() {
        final Map<String, DataSource> result = new HashMap<>(3, 1);
        result.put("ds_master", createDataSource("dev"));
        result.put("ds_slave_0", createDataSource("dev"));
        result.put("ds_slave_1", createDataSource("dev"));
        return result;
    }

    private static DataSource createDataSource(final String dataSourceName) {

        DruidDataSource result = new DruidDataSource();
        result.setDriverClassName(com.mysql.jdbc.Driver.class.getName());
        result.setUrl(URL_PREFIX + dataSourceName);
        result.setUsername(USER_NAME);
        result.setPassword(PASSWORD);
        return result;
    }
`

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
sharing jdbc 2.0.3
druid 1.1.9
### Actual behavior （实际运行的结果是）

Caused by: java.lang.NullPointerException: null
	at io.shardingjdbc.spring.boot.SpringBootConfiguration.setDataSourceMap(SpringBootConfiguration.java:55) ~[sharding-jdbc-core-spring-boot-starter-2.0.3.jar:na]
	at io.shardingjdbc.spring.boot.SpringBootConfiguration.setEnvironment(SpringBootConfiguration.java:49) ~[sharding-jdbc-core-spring-boot-starter-2.0.3.jar:na]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:106) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 15 common frames omitted

**Comment by jixiaod** [comment]
已解决

**Comment by terrymanu** [comment]
please give some information to describe how to resolve it

**Comment by terrymanu** [comment]
duplicated with #623

**Comment by xie-summer** [comment]
@jixiaod  怎么解决的？求教
