### ISSUE TITLE
spring boot 2.0 支持

### ISSUE THREAD

**Issue by ooknight** [shardingjdbc/sharding-jdbc#652]
### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
io.shardingjdbc : sharding-jdbc-core-spring-boot-starter : 2.0.3
org.springframework.boot : spring-boot-dependencies : 2.0.0.RELEASE

### Expected behavior （您预期的结果是）
正常运行

### Actual behavior （实际运行的结果是）
java.lang.ClassNotFoundException: org.springframework.boot.bind.RelaxedPropertyResolver

### Steps to reproduce the behavior （可重现问题的操作步骤）
虽然是spring本身兼容性的问题,还是希望能支持下
参考 : https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#migrating-from-1x-to-20

**Comment by apgzs** [comment]
这个有没有临时的解决办法

**Comment by terrymanu** [comment]
fixed at 2.1.0

**Comment by apgzs** [comment]
when the 2.1.0  releases

**Comment by apgzs** [comment]
When is version 2.1.0 released

**Comment by fangdong116** [comment]
问题还存在，sharding-jdbc-core-spring-boot-starter 有新的版本吗，我用的2.03还是报错？
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.bind.RelaxedPropertyResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_77]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_77]
	... 82 common frames omitted
