### ISSUE TITLE
suggest sharding jdbc support "show" keyword

### ISSUE THREAD

**Issue by bbenguo** [shardingjdbc/sharding-jdbc#712]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
2.0.3
### Expected behavior （您预期的结果是）
support show table structure expresses like "SHOW TABLES LIKE 'table_name'" or "SHOW CREATE TABLE table_name"
### Actual behavior （实际运行的结果是）
io.shardingjdbc.core.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'SHOW'
### Steps to reproduce the behavior （可重现问题的操作步骤）
private static boolean isTableExists(Connection connection, String tableName) throws SQLException{
        String sql = "SHOW TABLES LIKE '" + tableName + "'";
        logger.debug("check if the table is exists: {}", sql);
        Statement statement = connection.createStatement();
        try {
            ResultSet resultSet = statement.executeQuery(sql);
            return resultSet.next();
        }
        catch (SQLException exp) {
            logger.debug("table {} is not exits.", tableName);
        }
        finally {
            statement.close();
        }
        return false;
    }
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by bbenguo** [comment]
io.shardingjdbc.core.parsing.parser.exception.SQLParsingUnsupportedException: Not supported token 'SHOW'.
	at io.shardingjdbc.core.parsing.parser.sql.SQLParserFactory.newInstance(SQLParserFactory.java:57)
	at io.shardingjdbc.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:50)
	at io.shardingjdbc.core.routing.router.ParsingSQLRouter.parse(ParsingSQLRouter.java:74)
	at io.shardingjdbc.core.routing.StatementRoutingEngine.route(StatementRoutingEngine.java:47)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingStatement.generateExecutor(ShardingStatement.java:191)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingStatement.executeQuery(ShardingStatement.java:97)
	at com.meicloud.saas.base.ShardingUtil.isTableExists(ShardingUtil.java:109)

**Comment by terrymanu** [comment]
duplicate with #609
