### ISSUE TITLE
Proxy raised an out of bound exception

### ISSUE THREAD

**Issue by tuohai666** [shardingjdbc/sharding-jdbc#750]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Jdbc do you using?（您使用的Sharding-Jdbc版本为？）
dev

### Expected behavior （您预期的结果是）
Read data correctly from the ByteBuf of sharding-proxy.

### Actual behavior （实际运行的结果是）
[WARN ] 17:20:14.713 [nioEventLoopGroup-5-3] i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.shardingjdbc.proxy.frontend.mysql.MySQLFrontendHandler$1@10d19d69
java.lang.IndexOutOfBoundsException: readerIndex(1040) + length(1) exceeds writerIndex(17): PooledUnsafeDirectByteBuf(ridx: 0, widx: 17, cap: 2048)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.shardingjdbc.proxy.transport.mysql.packet.MySQLPacketPayload.readInt1(MySQLPacketPayload.java:51) ~[classes/:na]
	at io.shardingjdbc.proxy.frontend.mysql.MySQLFrontendHandler$1.run(MySQLFrontendHandler.java:69) ~[classes/:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

### Steps to reproduce the behavior （可重现问题的操作步骤）
This Exception bust randomly, but not difficult to be reproduced by continuously send message to sharding-proxy for not a very long time.

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
https://github.com/shardingjdbc/sharding-proxy-example

Code should based on https://github.com/shardingjdbc/sharding-jdbc-example
（代码请基于 https://github.com/shardingjdbc/sharding-jdbc-example）

**Comment by tuohai666** [comment]
The Decode method of ByteToMessageDecoder "decode the from one ByteBuf to an other. This method will be called till either the input ByteBuf has nothing to read when return from this method or till nothing was read from the input link ByteBuf." -- from java doc

Our original code didn't read all the bytes out when readableBytes == realPacketLength, it pass the readableBytes directly to the pipeline. If the next handler didn't read the bytes in time, the decode method will be called to decode the remainder bytes. The second decoding on an incomplete message get a unpredictable message length that fire a out of bound exception.

A general way to solve this problem is to setSingleDecode(true) of ByteToMessageDecoder object, but we use ByteToMessageCodec instead of ByteToMessageDecoder. So we need to read out all the bytes before decode() is finish.

A similar issue in stackoverflow:
https://stackoverflow.com/questions/26604579/netty-bytetomessagecodecbytebuf-decoding-message-twice-partially/49992042#49992042
I have appended an alternative answer for those who use ByteToMessageCodec that can't implement the setSingleDecode method.
